import {Mail} from 'lucide-react'
import {FormEvent,useState} from 'react'
import {Link} from 'react-router-dom'
import {api} from '@/services/api'
import {Button} from '@/components/ui/Button'
import {AuthShell} from '@/components/layout/AuthShell'
export function ForgotPasswordPage(){
  const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const body:any=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});setMessage(body.message||'If an account exists for that email, a password reset link has been sent.')}catch(err){setError(err instanceof Error?err.message:'Unable to request password reset')}finally{setBusy(false)}}
  return <AuthShell title={<>Reset access securely.</>} description="Enter your registered email. We’ll create a secure, expiring password-reset link."><form onSubmit={submit} className="mx-auto w-full max-w-md"><span className="text-[11px] font-extrabold tracking-[0.14em] text-violet-600">PASSWORD RECOVERY</span><h2 className="mt-2 text-3xl font-extrabold text-slate-900">Forgot your password?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Enter the email associated with your account.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}<label className="mt-7 block"><span className="mb-2 block text-xs font-bold text-slate-700">Email address</span><div className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3.5 focus-within:border-violet-400 focus-within:ring-4 focus-within:ring-violet-100"><Mail size={18} className="text-slate-400"/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div></label><Button className="mt-6 w-full" disabled={busy}>{busy?'Sending…':'Send reset link'}</Button><p className="mt-6 text-center text-sm text-slate-500">Remembered it? <Link className="font-bold text-violet-600" to="/login">Back to sign in</Link></p></form></AuthShell>
}
