import {LockKeyhole} from 'lucide-react'
import {FormEvent,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {api} from '@/services/api'
import {Button} from '@/components/ui/Button'
import {AuthShell} from '@/components/layout/AuthShell'
export function ResetPasswordPage(){
  const [params]=useSearchParams(),token=params.get('token')||'';const [password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(!token)return setError('The reset token is missing.');if(password.length<8)return setError('Password must contain at least 8 characters.');if(password!==confirmPassword)return setError('Passwords do not match.');setBusy(true);try{const body:any=await api('/auth/reset-password',{method:'POST',body:JSON.stringify({token,password,confirmPassword})});setMessage(body.message||'Password reset successfully. You can now sign in.');setPassword('');setConfirmPassword('')}catch(err){setError(err instanceof Error?err.message:'Unable to reset password')}finally{setBusy(false)}}
  return <AuthShell title={<>Choose a new password.</>} description="Reset links expire and can only be used once. Existing refresh sessions are revoked after a successful reset."><form onSubmit={submit} className="mx-auto w-full max-w-md"><span className="text-[11px] font-extrabold tracking-[0.14em] text-violet-600">NEW PASSWORD</span><h2 className="mt-2 text-3xl font-extrabold text-slate-900">Reset password</h2><p className="mt-2 text-sm leading-6 text-slate-500">Choose a strong new password for your CampusSpark account.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}<div className="mt-7 space-y-5">{[['New password',password,setPassword],['Confirm new password',confirmPassword,setConfirmPassword]].map(([label,value,setter]:any)=><label className="block" key={label}><span className="mb-2 block text-xs font-bold text-slate-700">{label}</span><div className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3.5 focus-within:border-violet-400 focus-within:ring-4 focus-within:ring-violet-100"><LockKeyhole size={18} className="text-slate-400"/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" type="password" minLength={8} required value={value} onChange={e=>setter(e.target.value)}/></div></label>)}</div><Button className="mt-6 w-full" disabled={busy||!token}>{busy?'Updating…':'Set new password'}</Button><p className="mt-6 text-center text-sm text-slate-500"><Link className="font-bold text-violet-600" to="/login">Return to sign in</Link></p></form></AuthShell>
}
