import {BookOpen,Building2,CalendarDays,Coins,PackageCheck,RotateCcw,Users} from 'lucide-react'
import {StatCard} from '@/components/ui/StatCard'
import {ApiError,ApiLoading,EmptyState} from '@/components/common/ApiState'
import {PageHeading} from '@/components/common/PageHeading'
import {useAsyncData} from '@/hooks/useAsyncData'
import {api} from '@/services/api'
import {mapEvent} from '@/services/mappers'
export function AdminDashboardPage(){
  const {data,loading,error}=useAsyncData(async()=>{const b:any=await api('/dashboard/admin',{auth:true});return{stats:b.data.stats,popularEvents:(b.data.popularEvents||[]).map(mapEvent)}},[])
  if(loading)return <ApiLoading/>;if(error||!data)return <ApiError message={error||'Unable to load admin dashboard'}/>
  const s=data.stats
  return <><PageHeading eyebrow="ADMIN CONSOLE" title="Platform overview" description="Manage users, organizers, events, books, borrow returns, rewards and platform activity."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Users" value={Number(s.totalUsers||0).toLocaleString()} icon={<Users size={21}/>}/><StatCard label="Active users" value={Number(s.activeUsers||0).toLocaleString()} icon={<Users size={21}/>}/><StatCard label="Organizers" value={Number(s.totalOrganizers||0).toLocaleString()} icon={<Building2 size={21}/>}/><StatCard label="Active organizers" value={Number(s.activeOrganizers||0).toLocaleString()} icon={<Building2 size={21}/>}/><StatCard label="Total events" value={Number(s.totalEvents||0).toLocaleString()} icon={<CalendarDays size={21}/>}/><StatCard label="Registrations" value={Number(s.totalRegistrations||0).toLocaleString()} icon={<CalendarDays size={21}/>}/><StatCard label="Books" value={Number(s.totalBooks||0).toLocaleString()} icon={<BookOpen size={21}/>}/><StatCard label="Active book borrows" value={Number(s.activeBookBorrows||0).toLocaleString()} icon={<BookOpen size={21}/>}/><StatCard label="Book return requests" value={Number(s.returnRequests||0).toLocaleString()} icon={<RotateCcw size={21}/>}/><StatCard label="Points distributed" value={Number(s.pointsDistributed||0).toLocaleString()} icon={<Coins size={21}/>}/><StatCard label="Pending redemptions" value={Number(s.pendingRedemptions||0).toLocaleString()} icon={<PackageCheck size={21}/>}/><StatCard label="Delivered redemptions" value={Number(s.deliveredRedemptions||0).toLocaleString()} icon={<PackageCheck size={21}/>}/></div><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-900">Popular events</h2><p className="mt-1 text-xs text-slate-500">Ranked by actual registration count.</p><div className="mt-4">{data.popularEvents.length===0?<EmptyState title="No event activity" message="No events have registration activity yet."/>:<div className="divide-y divide-slate-100">{data.popularEvents.map(e=><div key={e.id} className="flex items-center justify-between gap-4 py-4"><div><strong className="block text-sm text-slate-800">{e.title}</strong><small className="mt-1 block text-xs text-slate-400">{e.registered} registrations</small></div><b className="text-sm text-violet-700">{e.registered}</b></div>)}</div>}</div></section></>
}
