import {Building2,Pencil,Search,Trash2} from 'lucide-react'
import {FormEvent,useState} from 'react'
import {Badge} from '@/components/ui/Badge'
import {Button} from '@/components/ui/Button'
import {FieldLabel,SelectInput,TextInput} from '@/components/common/FormField'
import {ApiError,ApiLoading,EmptyState} from '@/components/common/ApiState'
import {PageHeading} from '@/components/common/PageHeading'
import {TableShell,Table,THead,TH,TD} from '@/components/common/DataTable'
import {useAsyncData} from '@/hooks/useAsyncData'
import {api} from '@/services/api'
import {mapUser} from '@/services/mappers'
import type {User} from '@/types'

export function OrganizersPage(){
  const [search,setSearch]=useState(''),[editing,setEditing]=useState<User|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[actionError,setActionError]=useState('')
  const [form,setForm]=useState({name:'',email:'',phone:'',status:'ACTIVE'})
  const {data,loading,error,refresh}=useAsyncData(async()=>{const b:any=await api(`/admin/organizers${search?`?search=${encodeURIComponent(search)}`:''}`,{auth:true});return(b.data||[]).map(mapUser)},[search])
  function openEdit(org:User){setEditing(org);setForm({name:org.name,email:org.email,phone:org.phone||'',status:org.status||'ACTIVE'});setActionError('');setMessage('')}
  async function save(e:FormEvent){e.preventDefault();if(!editing)return;setBusy(true);setActionError('');try{await api(`/admin/organizers/${editing.id}`,{method:'PATCH',auth:true,body:JSON.stringify({name:form.name,email:form.email,phone:form.phone||null,status:form.status})});setMessage('Organizer updated successfully.');setEditing(null);await refresh()}catch(err){setActionError(err instanceof Error?err.message:'Unable to update organizer')}finally{setBusy(false)}}
  async function status(id:string,value:'ACTIVE'|'INACTIVE'|'SUSPENDED'){try{setActionError('');await api(`/admin/organizers/${id}/status`,{method:'PATCH',auth:true,body:JSON.stringify({status:value})});await refresh()}catch(err){setActionError(err instanceof Error?err.message:'Unable to update status')}}
  async function remove(org:User){if(!confirm(`Delete organizer “${org.name}”? This also removes organizer-owned events, books and related activity.`))return;try{setActionError('');await api(`/admin/organizers/${org.id}`,{method:'DELETE',auth:true});setMessage('Organizer deleted successfully.');await refresh()}catch(err){setActionError(err instanceof Error?err.message:'Unable to delete organizer')}}
  return <><PageHeading eyebrow="ORGANIZERS" title="Organizer management" description="Review self-registered organizers, edit details, activate, suspend or delete accounts."/>
    {message&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</div>}{actionError&&<ApiError message={actionError}/>} 
    {editing&&<form onSubmit={save} className="mb-6 rounded-3xl border border-violet-200 bg-gradient-to-br from-white via-violet-50 to-blue-50 p-6 shadow-sm"><div className="mb-5"><h2 className="text-lg font-extrabold text-slate-900">Edit organizer</h2><p className="mt-1 text-xs text-slate-500">Update organizer account information and access status.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><FieldLabel label="Name"><TextInput required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></FieldLabel><FieldLabel label="Email"><TextInput required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></FieldLabel><FieldLabel label="Phone"><TextInput value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></FieldLabel><FieldLabel label="Status"><SelectInput value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="SUSPENDED">Suspended</option></SelectInput></FieldLabel></div><div className="mt-5 flex gap-3"><Button disabled={busy}>{busy?'Saving…':'Save changes'}</Button><button type="button" onClick={()=>setEditing(null)} className="rounded-xl px-4 text-sm font-bold text-slate-500 hover:bg-white">Cancel</button></div></form>}
    <div className="mb-5 flex max-w-md items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 focus-within:border-violet-400 focus-within:ring-4 focus-within:ring-violet-100"><Search size={17} className="text-slate-400"/><input className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Search organizer or email…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading&&<ApiLoading/>}{error&&<ApiError message={error}/>} {!loading&&!error&&(data||[]).length===0&&<EmptyState title="No organizers found" message="Organizer accounts will appear here after self-registration."/>}{(data||[]).length>0&&<TableShell><Table><THead><tr><TH>Organizer</TH><TH>Events</TH><TH>Status</TH><TH>Actions</TH></tr></THead><tbody>{(data||[]).map(org=><tr key={org.id}><TD><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 text-blue-700"><Building2 size={18}/></div><div><strong className="block text-slate-800">{org.name}</strong><small className="mt-1 block text-xs text-slate-400">{org.email}</small></div></div></TD><TD>{org.eventsCount??0}</TD><TD><Badge tone={org.active?'green':'gray'}>{org.status||'INACTIVE'}</Badge></TD><TD><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-1 text-xs font-bold text-violet-600" onClick={()=>openEdit(org)}><Pencil size={13}/> Edit</button><button className="text-xs font-bold text-emerald-600" onClick={()=>status(org.id,'ACTIVE')}>Activate</button><button className="text-xs font-bold text-amber-600" onClick={()=>status(org.id,'SUSPENDED')}>Suspend</button><button className="inline-flex items-center gap-1 text-xs font-bold text-red-600" onClick={()=>remove(org)}><Trash2 size={13}/> Delete</button></div></TD></tr>)}</tbody></Table></TableShell>}</>
}
